import platform
import os

def clear(user_platfrom = platform.platform()):
    if user_platfrom == "Windows":
        os.system("cls")
        print("Neden linux kullanmıyorsun ):<")
    else:
        os.system("clear")

clear()

class kelimeler:
    kelimeler = {
        "Appearance" : "Görünüş",
        "Be late" : "Geç kalmak",
        "Blonde" : "Sarışın",
        "Buy a present" : "Hediye almak",
        "Care" : "Umursamak",
        "Change mind" : "Fikir değiştirmek",
        "Close" : "Kapatmak, Yakın",
        "Curly" : "Kıvırcık",
        "Cute" :  "Tatlı",
        "Do sports" : "Spor yapmak",
        "Forget easily" : "Kolayca unutmak",
        "Get high marks" : "Yüksek not almak",
        "Get on well" : "İyi geçinmek",
        "Hair" : "Saç",
        "Handsome" : "Yakışıklı",
        "Headscarf" : "Başörtüsü",
        "Help people" : "İnsanlara yardım etmek",
        "Make a joke" : "Şaka yapmak",
        "Make friends" : "Arkadaş edinmek",
        "Nice" : "Güzel",
        "Personality" : "Kişilik",
        "Plump" : "Balık etli, tombul",
        "Share" : "Paylaşmak",
        "Smile" : "Gülümsemek",
        "Spend time" : "Zaman harcamak",
        "Straight"  : "Düz",
        "Study hard" : "Sıkı çalışmak",
        "Tell a lie" : "Yalan söylemek",
        "Tell the truth" : "Doğruyu söylemek",
        "Wavy" : "Dalgalı",
        "He is fine" : "O iyi",
        "He is really fine" : "O gerçekten iyi",
        "I hope" : "Umuyorum ki",
        "Of course" : "Elbette",
        "What about you?" : "Ya sen",
        "What does he/she look like?" : "O nasıl görünüyor?",
        "What is he/she like" : "O nasıl biridir?",
        "Achieve" : "Başarmak",
        "Beat" : "Yenmek",
        "Bow" : "Yay",
        "Camping" : "Kamp yapmak", 
        "Climbing" : "Tırmanmak",
        "Coach" : "Koç",
        "Court" : "Kort, Saha",
        "Daily routine" : "Günlük rutin",
        "Do exercise" : "Egzersiz yapmak",
        "Draw" : "Beraberelik", 
        "Eat healthy food" : "Sağlıklı yiyecekler yemek",
        "Equipment" : "Ekipman",
        "Go on a diet" : "Diyet yapmak",
        "Have an injury" : "Yaralanmak",
        "Helmet" : "Kask",
        "Hiking" : "Tırmanmak",
        "Individual sports" : "Kişisel sporlar",
        "Indoor sports" : "Kapalı alan sporlar",
        "Need" : "İhtiyaç (duymak)",
        "Net" : "Ağ",
        "Outdoor sports" : "Açık alan sporlar",
        "Score a goal" : "Gol yapmak",
        "Scuba diving" : "Tüplü dalış yapmak",
        "Skateboarding" : "Kaykay yapmak",
        "Snowboarding" : "Kar kayağı",
        "Surfing" : "Sörf yapmak",
        "Team sports" : "Takım sporları",
        "Train" : "Antreman yapamk",
        "Win a gold medal" : "Altın madalya kazanmak",
        "Workout" : "İdman, antreman",
        "Alone" : "Yalnız",
        "Award" : "Ödül",
        "Band" : "Grup ,Topluluk, Bando",
        "Be born" : "Doğmak",
        "Become a proffesor": "Profesör olmak",
        "Bioghraphy" : "Biografi",
        "Compose" : "Bestelemek", 
        "Die" : "Ölmek",
        "Discover" : "Keşfetmek",
        "Education" : "Eğitim",
        "Famous" : "Ünlü",
        "Found" : "Bulmak",
        "Get married" : "Evlenmek",
        "Get retired" : "Emekli olmak",
        "Graduate from universty" : "Üniversiteden mezun olmak",
        "Grow up" : "Büyümek",  
        "Have a career" : "Kariyer yapmak",
        "Have children" : "Çocuk sahibi olmak",
        "Have a great talent" : "Büyük bir yetenk sahibi olmak",
        "Invent" : "Keşfetmek",
        "Learn"  : "Öğrenmek",
        "Life" : "Hayat, Yaşam",
        "Live" : "Yaşamak",
        "Move" : "Taşınmak",
        "Perform" : "Sergilemek",
        "Raise children" : "Çocuk yetiştirmek",
        "Receive" : "Almak",
        "Win an award" : "Ödül kazanmak" ,
        "Work on" : "Üzerine çalışmak",
        "Bye" : "Hoşça Kal",
        "Let me think" : "Bir düşüneyim",
        "Right" : "Doğru",
        "You're welcome" : "Rica ederim",
        "Ape" : "Maymun",
        "Bear" : "Ayı",
        "Become extinct": "Nesli tükenmek",
        "Bird" : "Kuş",
        "Cage" : "Kafes",
        "Cave" : "Mağara",
        "Claw" : "Pençe",
        "Crow" : "Karga",
        "Desert" : "Çöl",
        "Destroy" : "Yok etmek",
        "Eat" : "Yemek",
        "Endangered" : "Nesli tükenmekte olan",
        "Fur" : "Kürk",
        "Grassland" : "Otlak",
        "Hunt" : "Av",
        "Land" : "Kara, toprak",
        "Mammal" : "Memeli",
        "Mammoth" : "Mamut",
        "Mountain" : "Dağ",
        "Paw" : "Pati",
        "Protect" : "Korumak",
        "Reptile" : "Sürüngen",
        "Seal" : "Fok balığı",
        "Squirrel" : "Sincap",
        "Stork" : "Leylek",
        "Stripe" : "Şerit",
        "Trunk" : "Fil hortumu",
        "Tusk" : "Fil dişi",
        "Wild animal" : "Vahşi hayvan",
        "Wing" : "Kanat",
        "How amazing" : "Ne harika", 
        "I'm really sorry" : "Gerçekten üzgünüm",
        "Amusing" : "Eğlenceli",
        "Boring" : "Sıkıcı",
        "Cartoon" : "Çizgi film",
        "Commercial" : "Reklam",
        "Cookery programme" : "Yemek programı",
        "Discussion programme" : "Tartışma programı",
        "Documentary" : "Belgesel",
        "Dull" : "Sıkıcı",
        "Educational" : "Eğitici",
        "Enjoyable" : "Zevkli",
        "Entertaining" : "Eğlenceli",
        "Exciting" : "Heyecanlı",
        "Fantastic" : "Fantastik",
        "Funny" : "Eğlenceli",
        "Horror movie" : "Korku filmi",
        "Interesting" : "İlgi çekici",
        "Mentally disabled" : "Zihinsel engelli",
        "News" : "Haberler",
        "Nonsense" : "Saçma",
        "Prefer" : "Tercih etmek",
        "Quiz show" : "Bilgi programı",
        "Reality show" : "Çok uzun yazmaya uğraşmayacağım",
        "Sci-fi series" : "Bilim kurgu serisi",
        "Series" : "Dizi",
        "Silly" : "Saçma",
        "Sitcom" : "Olay komedisi",
        "Soap opera" : "Pembe dizi",
        "Sports programme" : "Spor programı",
        "Talk show" : "Sohbet programı",
        "Weather forecast" : "Hava tahmin raporu",
        "Accept" : "Kabul etmek",
        "Arrange" : "Ayarlamak",
        "Attend" : "Katılmak",
        "Beverage" : "İçecek",
        "Celebration" : "Kutlama",
        "Chocolate" : "Çikolata",
        "Come to the party" : "Partiye gelmek",
        "Decorate" : "Dekore etmek",
        "Engagement party" : "Nişan töreni",
        "Fancy dress party" : "Kostüm partisi",
        "Farewell party" : "Veda partisi",
        "Guest list" : "Ziyaretçi listesi",
        "Host" : "Yönetici",
        "Invitation card" : "Davet kardı",
        "Invite" : "Davet etmek",
        "Join" : "Katımak",
        "Make a cake" : "Kek yapmak",
        "Need" : "İhtiyaç duymak",
        "Order a cake" : "Kek sipariş etmek",
        "Organize a party" : "Parti düzenlemek",
        "Place" : "Yer",
        "Preparation" : "Hazırlık",
        "Prepare" : "Hazırlamak",
        "Present" : "Hediye",
        "Refuse" : "Reddetmek",
        "Start" : "Başlatmak",
        "Time" : "Zaman",
        "Wedding anniversary" : "Evlilik yıldönümü",
        "Welcome party" : "Hoşgeldin partisi",
        "Wrap a present" : "Hediye paketlemek",
        "Alright" : "Peki",
        "Congratulations" : "Tebrikler",
        "Could you say that again, please?" : "Bunu tekrar söyleyebilir misin, lütfen?",
        "Don't worry" : "Endişelenme",
        "Hope to see you tomorrow" : "Umarım yarın görüşürüz",
        "Hurry up!" : "Acele et!",
        "Is everything ok?" : "Her şey yolunda mı?",
        "No problem at all" : "Hiç sorun değil",
        "Oh my god!" : "Aman tanrım!",
        "OK, but just a few, please" : "Tamam, sadece birkaç tane lütfen",
        "Okay, here you are" : "Tamam, buyurun",
        "Sounds good" : "Kulağa iyi geliyor.",
        "Take care" : "Kendine iyi bak",
        "Thanks in advance." : "Şimdiden teşekkürler.",
        "What's up?" : "Naber?",
        "Yes, please. Just a little.": "Evet, lütfen. Sadece biraz.",
        "Yes, you are right." : "Evet haklısın.",
        "Yes. Why not? A few please." : "Evet, neden olmasın? Birkaç tane, lütfen.",
        "Adopt a pet" : "Evcil hayvan sahiplenmek",
        "Alien" : "Uzaylı",
        "Become popular" : "Popüler hale gelmek",
        "Brain to brain transmission" : "Beyinden beyine aktarma",
        "Buy a house" : "Ev satın almak",
        "Chip" : "Çip",
        "Create a company" : "Şirket kurmak",
        "Do hobbies" : "Hobi yapmak",
        "Dream" : "Rüya",
        "Sans" : "Sans",
        "Earn money" : "Para kazanmak",
        "Education" : "Eğitim",
        "Expectation" : "Beklenti",
        "Find a cure" : "Bir tedavi bulmak",
        "Find a job" : "Bir iş bulmak",
        "Food pills" : "Yiyecek hapları",
        "Future" : "Gelecek",
        "Get a diploma" : "Diploma almak",
        "Health" : "Sağlık",
        "Improvement" : "Ilerleme",
        "Meet" : "Tanışmak, karşılaşmak",
        "Poor" : "Fakir",
        "Predict" : "Tahmin etmek",
        "Probably" : "Sanırım",
        "Run a business" : "Bir iş yönetmek",
        "Self-driving car" : "Kendini süren araba",
        "Space" : "Uzay",
        "Travel in time" : "Zamanda yolculuk",
        "Use" : "Kullanmak",
        "Work for nature" : "Doğa için çalışmak",
        "Do you really think so?" : "Gerçekten öyle mi düşünüyorsun?",
        "I don't think so." : "Ben öyle düşünmüyorum.",
        "I hope not." : "Umarım değildir.",
        "I hope so." : "Umarım ki",
        "I'm doing fine" : "İyiyim.",
        "Im looking forward to hearing you." : "Cevabınızı bekliyorum",
        "How interesting, isn't it?" : "Ne kadar da ilginç, değil mi?",
        "Borrow a book" : "Kitap ödünç almak",
        "Busy" : "Meşgul",
        "Buy a camera" : "Fotoğraf makinesi satın almak",
        "Buy cookies" : "Kurabiye satın almak",
        "City hall" : "Belediye binası",
        "Department store" : "Büyük mağaza",
        "Do shopping" : "Alışveriş yapmak",
        "Draw money" : "Para çekmek",
        "Enjoy" : "Beğenmek",
        "Find" : "Bulmak",
        "Fire station" : "İtfaiye",
        "Greengrocer's" : "Manav",
        "Have fun" : "Eğlenmek",
        "Historical" : "Tarihi",
        "Lose a wallet" : "Cüzdan kaybetmek",
	    "Meet friends"  : "Arkadaşlarınla buluşmak",
        "Movie theatre" : "Sinema",
        "Municipiality" : "Belediye",
        "Painkiller" : "Ağrı kesici",
        "Police station" : "Polis istasyonu",
        "Public buildings" : "Kamu binaları",
        "Report a crime" : "Suç bildirmek",
        "Ride a roller coaster" : "Hız trenine binmek",
        "See the mayor" :"Belediye başkanını görmek",
        "Send a letter" : "Mektup göndermek",
        "Shopping mall" : "Alışveriş merkezi",
        "Try" : "Denemek",
        "Visit" : "Ziyaret etmek",
        "Wedding ceremony" : "Nikah töreni",
        "Its okay with me." : "Benim için uygun.",
        "Long time no see." : "Görüşmeyeli uzun zaman oldu",
        "Poor you!" : "Yazık sana!",
        "Sure, why not?" : "Elbette, neden olmasın?",
        "Thank godness." : "Çok şükür.",
        "Breathe" : "Nefes almak", 
        "Buy a rechargeable battery" : "Şarjlı pil almak",
        "Cause" : "Sebep olmak",
        "Climate change" : "İklim değişikliği",
        "Cut down trees" : "Ağaç kesmek",
        "Deforestation"  : "Ormanların tahrip olması",
        "Destroy forests": "Ormanları yok etmek",
        "Enviroment" : "Çevre",
        "Exhaust fume" : "Egzoz gazı",
        "Keep clean" : "Temiz tutmak", 
        "Litter" : "Çöp",
        "Plant a tree" : "Ağaç dikmek",
        "Pollute" : "Kirletmek",
        "Practical" : "Pratik",
        "Prevent" : "Önlemek",
        "Produce" : "Üretmek",
        "Protect" : "Korumak",
        "Recycle" : "Geri dönüştürmek",
        "Reduce" : "Azaltmak",
        "Rise" : "Yükselmek",
        "Save" : "Kurtarmak",
        "Sort out" : "Ayırmak, düzenlemek",
        "Stop" : "Durdurmak, durmak",
        "Take action" : "Harekete geçmek",
        "Threaten" : "Tehdit etmek",
        "Throw rubbish" : "Çöp atmak",
        "Turn off" : "Kapatmak",
        "Use public transportation" : "Toplu taşıma kullanmak",
        "Waste energy" : "Enerji harcamak",
        "Water" : "Su",
        "Kıvanç" : "Kıvanç"
            }
     
    def __init__(self) -> None:
        for i in self.kelimeler:
            print(f"{i} : {self.kelimeler[i]}")
        return None

    def kelime_ara(self, string, saw=False) -> None:
        for i in self.kelimeler:
            if string.lower() in i.lower() or string.lower() in kelimeler.kelimeler[i].lower():
                print(f"{i} : {self.kelimeler[i]}")
                saw = True
        if not saw:
            print("Kelime bulunamadı.")
            return None

        
            

while True:
    try:
        userinput = input("Çıkmak için \"__q__\", kelime aratmak için kelimeyi, sözlüğü görmek için \"__dict__\" yazın.")
        if userinput == "__q__":
            break
        elif userinput == "__dict__":
            kelimeler()
        else:
            kelimeler.kelime_ara(self=kelimeler, string=userinput)
        input("Devam etmek için entera basın.")
        clear()
    except EOFError:
        try:
            clear()
            input("Çalıştırılabilirliğin sonu hatası.")
            clear()
        except Exception:
            print("Uygulama kapatılıyor.")
            break
    except KeyboardInterrupt:
        clear()
        input("Uygulama kapatılmak istendi.")
        clear()
    except Exception:
        clear()
        input("Tanımlanamayan hata.")
        clear()




   

